version: "3"

services:
  ros2:
    build:
      context: .
    image: ros2:latest
    container_name: ros2_cont
    network_mode: "host"
    privileged: true
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./examples:/home/dev/examples
    tty: true
    restart: always